apiVersion: apps/v1
kind: ReplicaSet
medadata:
  name: myapp-replicaset
  labels:
      app: myapp
      type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
